name: ğŸš€Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    # å¦‚æœä½ æƒ³è¦è¿›ä¸€æ­¥å®šä¹‰è§¦å‘æ¡ä»¶ã€è·¯å¾„ç­‰ï¼Œå¯ä»¥æŸ¥çœ‹æ–‡æ¡£
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: ğŸš€Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: ğŸ”§Install dependencies
        run: yarn install --frozen-lockfile
      - name: ğŸ”§Build website
        run: yarn build

      # éƒ¨ç½²åˆ° GitHub Pages çš„çƒ­é—¨é€‰æ‹©ï¼š
      # æ–‡æ¡£ï¼šhttps://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: ğŸš€Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # è¦å‘å¸ƒåˆ° `gh-pages` åˆ†æ”¯çš„æ„å»ºè¾“å‡ºï¼š
          publish_dir: ./build
          # ä¸‹é¢ä¸¤è¡Œä¼šå°†æ­¤æ¬¡éƒ¨ç½² commit çš„ä½œè€…è®¾ç½®ä¸ºå®˜æ–¹çš„
          # GH-Actions æœºå™¨äººï¼š
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # å¦‚æœä¸è®¾ç½®è¿™ä¸¤ä¸ªå­—æ®µï¼ŒGH actions æœºå™¨äººä¼šè¢«é»˜è®¤ä½¿ç”¨ã€‚
          # ä½ å¯ä»¥ç”¨è‡ªå·±çš„ç”¨æˆ·ä¿¡æ¯æ›¿æ¢å®ƒä»¬ã€‚
          # user_name: github-actions[bot]
          # user_email: 41898282+github-actions[bot]@users.noreply.github.com